# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 15:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logInIP', models.CharField(max_length=150)),
                ('logInTime', models.DateTimeField()),
                ('logOutTime', models.DateTimeField()),
                ('UserAgent', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserLogInfo',
                'verbose_name_plural': 'UserLogInfoes',
            },
        ),
    ]
